modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/Kotori316/InfChest/issues"
license = "MIT License (c) 2019-2023 Kotori316"
[[mods]]
modId = "infchest"
version = "${file.jarVersion}"
displayName = "InfChest"
displayURL = "https://github.com/Kotori316/InfChest"
credits = "Kotori316"
authors = "Kotori316"
description = '''
Add a infinite capacity chest.'''
[[dependencies.infchest]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.infchest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, )"
ordering = "NONE"
side = "BOTH"
