modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Kotori316/InfChest/issues"
license = "MIT License (c) 2019-2023 Kotori316"
[[mods]]
modId = "infchest"
version = "${file.jarVersion}"
displayName = "InfChest"
updateJSONURL = "https://version.kotori316.com/get-version/1.20.3/neoforge/infchest"
displayURL = "https://github.com/Kotori316/InfChest"
credits = "Kotori316"
authors = "Kotori316"
description = '''
Add a infinite capacity chest.'''
[[dependencies.infchest]]
modId = "neoforge"
mandatory = true
versionRange = "[20.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.infchest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.3, )"
ordering = "NONE"
side = "BOTH"
