modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Kotori316/InfChest/issues"
[[mods]] 
modId="infchest"
version="${file.jarVersion}"
displayName="InfChest"
displayURL="https://github.com/Kotori316/InfChest"
credits="Kotori316" 
authors="Kotori316" 
description='''
Add a infinite capacity chest.'''
[[dependencies.infchest]]
    modId="forge" 
    mandatory=true 
    versionRange="[25,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.infchest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"
