name: Java CI

on:
  push:
    branches:
      - "1.19-fabric"
    paths:
      - "scala/**"
      - "src/test/**"
      - "gradle.properties"
      - ".github/workflows/gradle.yml"
  pull_request:
    branches:
      - "1.19-fabric"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Permission
        run: chmod +x ./gradlew
      - name: Prepare Test dir
        run: mkdir -p build/test-results/test
      - name: Toolchain
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runGameTest
          cache-read-only: false
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/test-results/test/*.xml
          name: Test-Report-${{ matrix.java }}-${{ github.run_number }}
