# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.21.11" ]
  pull_request:
    branches: [ "1.21.11" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - platform: forge
            data: runRunDataGenData
          - platform: fabric
            data: runData
          - platform: neoforge
            data: runServerData
      fail-fast: false
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set executable
        run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - name: javaToolchains
        run: ./gradlew :${{ matrix.platform }}:javaToolchains
      - name: Check Version
        run: ./gradlew :${{ matrix.platform }}:checkReleaseVersion
      - name: Build with Gradle
        run: ./gradlew :${{ matrix.platform }}:build
      - name: Game Test
        if: ${{ matrix.platform != 'forge' }}
        run: ./gradlew :${{ matrix.platform }}:runGameTestServer
        env:
          RUN_GAME_TEST: true
      - name: Data Generation
        # Forge crashes in CI???
        # if: ${{ matrix.platform != 'forge' }}
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.data }}
        env:
          RUN_DATA_GEN: true
      - name: Common Data Generation
        if: ${{ matrix.platform == 'neoforge' }}
        run: |
          ./gradlew :${{ matrix.platform }}:runCommonData
          git diff --exit-code -- ./common/src/generated
        env:
          RUN_DATA_GEN: true
      - name: Check updated files
        run: git status
      - name: Check diff
        run: git diff --exit-code -- ./${{ matrix.platform }}/src/generated
      - name: Upload test reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: reports-${{ matrix.platform }}-${{ github.run_id }}-${{ github.run_number }}
          if-no-files-found: 'ignore'
          path: |
            ${{ matrix.platform }}/build/reports/tests/test/
            ${{ matrix.platform }}/build/test-results/
