name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true
      - name: Enable daemon
        run: sed -i -e 's/org.gradle.daemon=false/org.gradle.daemon=true/' gradle.properties
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Download Private Key
        run: gcloud storage cp gs://kotori316-resources/secring.gpg "${HOME}/secring.gpg"
      - name: Download JKS
        run: gcloud storage cp gs://kotori316-resources/kotori316_keystore.jks "${HOME}/kotori316_keystore.jks"
      - name: Download Public Key
        run: |
          gcloud storage cp gs://kotori316-resources/pgp_public.pub "${HOME}/pgp_public.pub"
          gpg --import "${HOME}/pgp_public.pub"
      - name: Get credentials
        id: get-secrets
        run: |
          key_id=$(gcloud secrets versions access latest --secret=signing-key-id)
          key_password=$(gcloud secrets versions access latest --secret=signing-password)
          jar_password=$(gcloud secrets versions access latest --secret=jar-sign-key-password)
          modrinth_token=$(gcloud secrets versions access latest --secret=modrinth_token)
          curseforge_token=$(gcloud secrets versions access latest --secret=curseforge_token)
          azure_token=$(gcloud secrets versions access latest --secret=azure_token)
          echo "::add-mask::${key_id}"
          echo "::add-mask::${key_password}"
          echo "::add-mask::${jar_password}"
          echo "::add-mask::${modrinth_token}"
          echo "::add-mask::${curseforge_token}"
          echo "::add-mask::${azure_token}"
          echo "key_id=${key_id}" >> $GITHUB_OUTPUT
          echo "key_password=${key_password}" >> $GITHUB_OUTPUT
          echo "jar_password=${jar_password}" >> $GITHUB_OUTPUT
          echo "modrinth_token=${modrinth_token}" >> $GITHUB_OUTPUT
          echo "curseforge_token=${curseforge_token}" >> $GITHUB_OUTPUT
          echo "azure_token=${azure_token}" >> $GITHUB_OUTPUT
      - name: Compile
        run: ./gradlew compileJava
      - name: Release
        run: >-
          ./gradlew
          -Psigning.secretKeyRingFile="${HOME}/secring.gpg"
          -Psigning.password="${KEY_PASSWORD}"
          -Psigning.keyId="${KEY_ID}"
          -PjarSign.keyLocation="${HOME}/kotori316_keystore.jks"
          -PjarSign.keyAlias="ko316"
          -PjarSign.storePass="${JAR_PASSWORD}"
          build publishToMavenLocal curseforge modrinth publish
        env:
          KEY_PASSWORD: ${{steps.get-secrets.outputs.key_password}}
          KEY_ID: ${{steps.get-secrets.outputs.key_id}}
          JAR_PASSWORD: ${{steps.get-secrets.outputs.jar_password}}
          AZURE_TOKEN: ${{steps.get-secrets.outputs.azure_token}}
          CURSE_TOKEN: ${{steps.get-secrets.outputs.curseforge_token}}
          MODRINTH_TOKEN: ${{steps.get-secrets.outputs.modrinth_token}}
      - name: Verify Build Files
        run: |
          for f in $(find ./ -name "*.asc") ; do
            echo "${f:0:-4}"
            gpg --verify "$f" "${f:0:-4}"
          done
      - name: Verify Forge Main Jar
        run: jarsigner -verify -keystore "${HOME}/kotori316_keystore.jks" "$(ls forge/build/libs/*.jar | grep -v "deobf" | grep -v "sources")" -strict
      - name: Verify Fabric Main Jar
        run: jarsigner -verify -keystore "${HOME}/kotori316_keystore.jks" "$(ls fabric/build/libs/*.jar | grep -v "deobf" | grep -v "sources")" -strict
      - name: Verify Maven Local
        run: |
          for f in $(find ~/.m2 -name "*.asc") ; do
            echo "${f:0:-4}"
            gpg --verify "$f" "${f:0:-4}"
          done
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: InfChest-Release-${{ github.run_number }}
          retention-days: 7
          path: |
            */build/*libs/*.jar
            */build/*libs/*.asc
      - name: Upload Local Maven
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: InfChest-Maven-${{ github.run_number }}
          retention-days: 1
          path: ~/.m2
