name: Release

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true
          add-job-summary: 'on-failure'
      - name: Enable daemon
        run: sed -i -e 's/org.gradle.daemon=false/org.gradle.daemon=true/' gradle.properties
      - name: Compile
        run: ./gradlew testClasses
      - name: GameTest
        run: ./gradlew runGameTest
      - name: Check version
        run: ./gradlew checkReleaseVersion
        env:
          RELEASE_DEBUG: false

  release:
    needs: [ check ]
    permissions:
      id-token: write
      contents: write
      packages: write
    # See https://github.com/Kotori316/common-script/blob/main/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@main'
    with:
      sign_check_command: 'assemble publishToMavenLocal'
      release_command: 'checkReleaseVersion assemble publishToMavenLocal curseforge modrinth registerVersion publish --continue'
      enable_signature_check: true
      java_version: '21'
    secrets: inherit
